import Navbar from "@/components/layout/Navbar";
import "./globals.css";
import Logo from "@/components/layout/Logo";
import "@fortawesome/fontawesome-free/css/all.min.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <header>
        <Navbar />
      </header>
      <html lang="en">
        <body>{children}</body>
      </html>
      <footer>nckldn</footer>
    </>
  );
}
